project:
  type: website
  output-dir: docs

website:
  title: "SWC-JA"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - quickguide.qmd
      - links.qmd
      - href: "https://swcarpentry-ja.github.io/"
        text: 日本語

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
