project:
  type: website
  output-dir: docs

website:
  title: "swcarpentry-ja.github.io"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - quickguide.qmd
      - links.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
