---
---

## Welcome to Software Carpentry JA

[Software Carpentry](https://software-carpentry.org/) is an international community that teaches research computing lessons through workshops. The Software Carpentry JA team translates English lessons into Japanese and provides information about Software Carpentry in Japan.

Our specific goals are to translate all the [Software Carpentry lessons](https://software-carpentry.org/lessons/) into Japanese, and to [hold workshops](https://software-carpentry.org/workshops/) **in Japanese** on a regular basis.

## Links for the translation project

We manage translations at on GitHub at [swcarpentry-ja/i18n](https://github.com/swcarpentry-ja/i18n).

All of the lessons indicated in "Lessons Currently in Translation" below are automatically updated when there is an update to [swcarpentry-ja/i18n](https://github.com/swcarpentry-ja/i18n).

If you wish to contribute to the translation project, please the the [Translation Quickguide](quickguide.qmd)

### Lessons Currently in Translation

- [R-gapminder](https://swcarpentry-ja.github.io/r-novice-gapminder/ja/)

- [git-novice](https://swcarpentry-ja.github.io/git-novice/ja/)

- [shell-novice](https://swcarpentry-ja.github.io/shell-novice/ja/)


